---
# tasks file for webapp

- name: installing httpd package
  package:
      name: "httpd"
      state: present

- name: starting httpd service
  service:
        name: "httpd"
        state: started

- name: copying web page 
  copy:
        src: "{{ role_path }}/files/index.html"
        dest: "/var/www/html"
        mode: 0775

- name: restarting httpd service
  service:
        name: "httpd"
        state: restarted
